# EPS: 
- Loss of precision occurs if the result is less than the resolution(minimum possible unit of value for a device/language).
- This occurs when code is converted to byte code and then back to original code.

# Helpful Trick
- Trick helpful here is to avoid use of very small fractions; rather upscale them and check for any possible difference as now it will be significant.
- Ex: (0.3 - 0.2 - 0.1) ----> (0.3 * 1e6 - 0.2 * 1e6 - 0.1 * 1e6) 

In [772]:
0.3 - 0.2 - 0.1

-2.7755575615628914e-17

In [773]:
(0.3 * 1e6 - 0.2 * 1e6 - 0.1 * 1e6)

0.0

# Functions 

# Ex-1

In [774]:
def check_prime(num):
    '''
    This is the docstring for this function
    It takes an number input and checks if it is Prime or not
    '''
    for x in range(2,int(num/2)):
#       print(x)
        if num%x == 0:
            return False
            #return x, "is a factor of", num
            break
    else:
        return True
        #return num, "is prime indeed. Yay!"

In [775]:
A = check_prime(53)
A

True

# Ex-2

In [776]:
nums = [12, 13, 15, 16, 5]
nums1 = [2, 3, 10, 30, 14]

In [777]:
def square(num):
    return num**2

In [778]:
square(10.5)
# Python is not a strictly typed language; It is an interpreted language
# Based on the type, it has to decide/interpret the output; This makes it a bit slow

110.25

In [779]:
#nums**2
#square(nums)
#--------------------------------------------------------------------------------------#
#These math operations don't work on a list; A numpy array would be able to handle this

# Naive ways......

In [780]:
sq = []
for num in nums:
    sq.append(square(num))
sq
#Not ideal for a large list; 
#Required is pre-initialisation like: sq = list(range(0,100000)) to avoid StackOverflow Error
#SOLUTION: List Comprehension

[144, 169, 225, 256, 25]

In [781]:
sq = list(range(0,len(nums)))
for k, num in enumerate(nums):
    sq[k] = square(num)
    #sq.append(square(num))
sq

[144, 169, 225, 256, 25]

In [782]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
sq = list(range(0,len(mat)))

for i, num in enumerate(mat):
    sq[i] = num[1]
sq

[2, 5, 8]

# List Comprehensions (Sophisticated ways......)

# Ex-1

In [783]:
ans = [square(num) for num in nums]
ans

[144, 169, 225, 256, 25]

# Ex-2

In [784]:
ans2 = [check_prime(num) for num in nums]
ans2

[False, True, False, False, True]

In [785]:
z = 10

In [786]:
# x is a required argument, y is an optional argument
def calc(x,y=5):
    global z
    z = 100
    return x*y*z, x+y+z

In [787]:
A,B = calc(2,3)
print('A:',A,', B:',B)

A: 600 , B: 105


In [788]:
C,D = calc(x=2,y=5)
# calc(y=5,x=2) also possible
# calc(y=5,2) or calc(2,x=5) not possible; keyword argument needs to follow the positional argument
print('C:',C,', D:',D)

C: 1000 , D: 107


In [789]:
#map function maps a function and parameter together
list(map(square,nums))

[144, 169, 225, 256, 25]

In [790]:
nums

[12, 13, 15, 16, 5]

In [791]:
#filter function filters out the elements agreeing with that function
list(filter(check_prime,nums))

[13, 5]

# LAMBDA Functions

In [792]:
print('nums:',nums,'\nnums1:',nums1)

nums: [12, 13, 15, 16, 5] 
nums1: [2, 3, 10, 30, 14]


In [793]:
#lamdda funtions are in-line functions(anonymous functions)
list(map(lambda x,y : x**2 + y**2,nums,nums1))

[148, 178, 325, 1156, 221]

In [794]:
#Not anonymous anymore; Avoid this as it isn't supposed to be stored
circ = lambda x,y : x**2 + y**2

In [795]:
list(map(circ,nums,nums1))

[148, 178, 325, 1156, 221]

In [796]:
x = [1,3,5]
y = [4.8, 11.3, 17.2]

# Arrays in Numpy
- 1D
    - 1D (Shape: (p,))
    - Vectors
        - Row Vector   (Shape: (1,n)): Single Row Array
        - Column Vector(Shape: (n,1)): Single Column Array
- 2D (Shape: (m,n))
- nD (Multi Dimensional Array where n >= 3) 

In [797]:
import numpy as np
arr = np.array(mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [798]:
arr*100

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [799]:
arr**6

array([[     1,     64,    729],
       [  4096,  15625,  46656],
       [117649, 262144, 531441]], dtype=int32)

In [800]:
arr.shape

(3, 3)

In [801]:
arr.dtype

dtype('int32')

In [802]:
arr.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [803]:
numlist = [1,2,3,4,5]
arr1d = np.array(numlist)
arr1d

array([1, 2, 3, 4, 5])

In [804]:
#Dimensions
arr1d.shape

(5,)

In [805]:
#Row Vector
RV = arr1d.reshape(1,5)
RV

array([[1, 2, 3, 4, 5]])

In [806]:
#Transpose gives Column Vector
#CV = RV.T
CV = arr1d.reshape(-1,1)
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [807]:
arr1d.mean()
arr1d.size

5

In [808]:
np.random.seed(101)
A = np.random.randint(0,100,16).reshape(4,4)
A.shape

(4, 4)

In [809]:
# Math operations like +,-,* happen element-wise
B = A[0]
B.shape

(4,)

In [810]:
# Array Multiplication
# 1.Normal(ELement-wise)
C = A*B
C

array([[9025,  121, 6561, 4900],
       [5985,  957, 6075,  630],
       [7315,  440,  324, 4410],
       [3800,  660, 7452, 4480]])

In [811]:
# 2.Matrix Multiplication
# i. Built-in: .dot()
A.dot(B)
A.dot(B.reshape(-1,1))

array([[20607],
       [13647],
       [12489],
       [16392]])

In [812]:
# ii. Numpy: np.matmul()
np.matmul(A,B.reshape(-1,1))

array([[20607],
       [13647],
       [12489],
       [16392]])

In [813]:
##############################PRACTICAL##############################
#Not Scalable Solution
#W1*=BAR(XY) - BAR(X) x BAR(Y) / ( BAR(SQ(X)) - SQ(BAR(X)) )
#W0* = BAR(Y) - (W1* X BAR(X))

#Vectorised Solution is good (Optimal values of model wts.)
#X and Y are numpy arrays
#X = [1,3,5]; Y=[4.8,11.3,17.2]
#W = inverse( transpose(x) x (x) ) x transpose(x) x (y) = answer
#np.linalg.inv()
x = np.array([[1,1],[1,3],[1,5]]).reshape(-1,2) #3x2
y = np.array([4.8,11.3,17.2]).reshape(-1,1) #3x1
aa = np.linalg.inv(x.T.dot(x)) #2x2
bb = aa.dot(x.T) # 2x3
w =  bb.dot(y) #2x1
x

array([[1, 1],
       [1, 3],
       [1, 5]])

In [814]:
x.dot(w)

array([[ 4.9],
       [11.1],
       [17.3]])

In [815]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()

In [816]:
LR.fit(x,y)

LinearRegression()

In [817]:
LR.coef_
#This is bcoz I'm using a Row Vector; always try to use CV in scikit

array([[0. , 3.1]])

In [818]:
 LR.intercept_

array([1.8])

In [819]:
LR.predict(x)

array([[ 4.9],
       [11.1],
       [17.3]])

### Broadcasting in Numpy

In [820]:
A1 = np.array([1,2,3])
B1 = 10
#B1 here braodcasts to every element of A1: [10,10,10]
A1 + B1 

array([11, 12, 13])

In [821]:
CV = np.array([1,2,3,4]).reshape(4,1)
CV

array([[1],
       [2],
       [3],
       [4]])

In [822]:
CV + A

array([[96, 12, 82, 71],
       [65, 89, 77, 11],
       [80, 43,  7, 66],
       [44, 64, 96, 68]])

# Indexing in Numpy
- In MATLAB, indexing starts from 1 and direction is Right to Left
- In PYTHON, indexing starts from 0 and direction is Top to Bottom

In [823]:
A[1,1] # Element at co-ordinates [1,1]
A[:,:] # All rows & all columns
A[:] #Linear indexing
A[1:3,1:3] # 1st and 3rd row & 1st and 3rd column
A[[1,3], [0,2]] # Mapping works as [1,0] and [3,2]

array([63, 92])

In [824]:
# Checks for all elements
A>50 

# Here, "and" operator won't work
#A[ (A>50) & (A<80) ] 

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [825]:
# Both work in same way
A.flatten()
A.ravel()

print(A)

# Sum along its diagonal
A.trace()

[[95 11 81 70]
 [63 87 75  9]
 [77 40  4 63]
 [40 60 92 64]]


250

In [826]:
# Diagonals from left to right/up to down
A.diagonal()
# np.flipud(A).diagonal()
# np.fliplr(A).diagonal()

v = [1,2,3,4,5]
np.diag(v)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [827]:
# Empty arrays of zeros or ones
np.zeros(5)
np.zeros((5,3))
np.zeros(A.shape)

np.ones(A.shape)
np.ones(A.shape)*np.nan

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [828]:
# Identity Matrix
np.eye(4)

A.dot(np.eye(A.shape[0]))

array([[95., 11., 81., 70.],
       [63., 87., 75.,  9.],
       [77., 40.,  4., 63.],
       [40., 60., 92., 64.]])

In [829]:
# Max and Min Element
A.min()
A.max()

# Index of Max and Min Element
A.argmin()
A.argmax()

0

In [830]:
#Statistical Functions
A.mean()
A.std()
A.var().round(2)

809.53

In [831]:
# Trignometric Functions
np.sin(A)
np.log(A)
np.log10(A)
np.exp(A)

array([[1.81123908e+41, 5.98741417e+04, 1.50609731e+35, 2.51543867e+30],
       [2.29378316e+27, 6.07603023e+37, 3.73324200e+32, 8.10308393e+03],
       [2.75851345e+33, 2.35385267e+17, 5.45981500e+01, 2.29378316e+27],
       [2.35385267e+17, 1.14200739e+26, 9.01762841e+39, 6.23514908e+27]])

In [832]:
# range vs arange function
list(range(0,10,2))

# arange doesn't give problems for fractional values
np.arange(0,10,2) 
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [833]:
# Find numbers b/w a specified range
# Here, 25 no.s b/w 0 and 10 (23 more and 0 and 10)
np.linspace(0,10,25).reshape(5,5).round(2)

# Generate 10 no.s b/w 10^0 and 10^3
np.logspace(0,3,10).round(2)

array([   1.  ,    2.15,    4.64,   10.  ,   21.54,   46.42,  100.  ,
        215.44,  464.16, 1000.  ])